host: "localhost"
port: 6333
similarity_top_k: 10
similarity_cutoff: 0.98
collection_name: "diglife"
api_key: "ac89ee8d-ba2a-4e31-bad7-021cf411c673"
model_name: "doubao-embedding-text-240715"

llm_model_name: "gemini-2.5-flash-preview-05-20-nothinking"
llm_api_key: ""
recommended_biographies_cache_max_leng: 2
recommended_cache_max_leng: 2
get_avatar_desc_url: "http://182.92.107.224:7000/api/inner/getAvatarDesc?userProfileId={user_profile_id}"
get_memory_desc_url: "http://182.92.107.224:7000/api/inner/getMemoryCards?userProfileId={user_profile_id}"